const MAX_BACKPACK_WEIGHT = 75;
const CROSSOVER_RATE = 0.53;
const MUTATION_RATE = 0.05;
const INITIAL_POPULATION = 10000;
const NUMBER_OF_GENERATIONS = 10000;
const SORTED_POPULATION = false;

module.exports = {
  MAX_BACKPACK_WEIGHT,
  CROSSOVER_RATE,
  MUTATION_RATE,
  INITIAL_POPULATION,
  NUMBER_OF_GENERATIONS,
  SORTED_POPULATION,
};
